# Generated by Django 2.2 on 2020-07-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitchhiker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='reserve_seat',
            field=models.BooleanField(default=0),
        ),
    ]
