# Generated by Django 2.2 on 2020-07-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitchhiker_app', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_comments', to='hitchhiker_app.User'),
        ),
    ]
